/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckTag: typeof import('./src/components/tag/checkTag.vue')['default']
    Color: typeof import('./src/components/color/index.vue')['default']
    Editor: typeof import('./src/components/editor/index.vue')['default']
    Image: typeof import('./src/components/image/index.vue')['default']
    Result: typeof import('./src/components/result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    Thumbnail: typeof import('./src/components/thumbnail/index.vue')['default']
    Upload: typeof import('./src/components/upload/index.vue')['default']
    UploadPictures: typeof import('./src/components/uploadPictures/index.vue')['default']
  }
}
